name: saveminecraft
version: 1.3
authors: [Blendydev]
main: me.blendy.saveminecraft.SaveMinecraft
commands:
  changeorg:
    description: Shows change.org signatures
    usage: /changeorg
  savemc:
    description: Main command
    usage: /savemc <subcommand>
